### ISSUE TITLE
Exception [42P01] SQLSTATE[42P01]: Undefined table

### ISSUE THREAD

**Issue by mikalj2009** [fintechstudios/davical-docker#5]
Im using the docker-compose example, and get following errors trying to access the web-page:

```
Exception [42P01] SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "awl_db_revision" does not exist
LINE 1: ...ECT schema_major, schema_minor, schema_patch FROM awl_db_rev...
                                                             ^
At line 94 of /usr/share/awl/inc/AwlDatabase.php
================= Stack Trace ===================
/usr/share/davical/htdocs/index.php[10] include()
/usr/share/davical/htdocs/always.php[311] AwlQuery->Exec()
/usr/share/awl/inc/AwlQuery.php[585] AwlQuery->Execute()
/usr/share/awl/inc/AwlQuery.php[396] AwlDatabase->query()
/usr/share/awl/inc/AwlDatabase.php[94] PDO->query()
```

docker-compose:

```
version: '3'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
  davical:
    image: fintechstudios/davical
    build: .
    ports:
      - '4080:80'
    depends_on:
      - postgres
    environment:
      PGHOST: 'postgres'
      PGPASSWORD: 'davical'
      # the following is only needed to run database migrations
      RUN_MIGRATIONS_AT_STARTUP: 'true'
      ROOT_PGUSER: 'postgres'
      ROOT_PGPASSWORD: 'postgres'
      DAVICAL_ADMIN_PASS: 'admin'
      DBA_PGUSER: 'davical_dba'
      DBA_PGPASSWORD: 'davical'
```
